# Workflow for building and deploying a Hugo site to S3
name: Deploy Hugo site to S3

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: "hugo_deploy"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Use 'true' if you don't need nested submodules
          fetch-depth: 0         # Fetch full history to ensure submodules are properly initialized

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ vars.HUGO_VERSION }}
          extended: true

      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
            --minify \
            --baseURL "${{ vars.SITE_BASE_URL }}/"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hugo-site
          path: ./public

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: hugo-site
          path: ./public

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GithubActions-MyHugoProject
          mask-aws-account-id: true

      - name: Sync to S3
        run: |
          aws s3 sync ./public/ s3://${{ vars.BUCKET_NAME }} \
            --delete \
            --cache-control max-age=31536000

      - name: CloudFront Invalidation
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ vars.CF_DISTRIBUTION_ID }} \
            --paths "/*"
